;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2014/7/27 14:07:08

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1006	1006	; AChartEngine index.html
#define IDH_1000	1000	; All Classes (AChartEngine) allclasses-frame.html
#define IDH_1001	1001	; All Classes (AChartEngine) allclasses-noframe.html
#define IDH_1004	1004	; API Help (AChartEngine) help-doc.html
#define IDH_1143	1143	; Class Hierarchy (AChartEngine) overview-tree.html
#define IDH_1002	1002	; Constant Field Values (AChartEngine) constant-values.html
#define IDH_1003	1003	; Deprecated List (AChartEngine) deprecated-list.html
#define IDH_1005	1005	; Index (AChartEngine) index-all.html
#define IDH_1142	1142	; Overview (AChartEngine) overview-summary.html
#define IDH_1141	1141	; Overview List (AChartEngine) overview-frame.html
#define IDH_1144	1144	; Serialized Form (AChartEngine) serialized-form.html
#define IDH_1051	1051	; ChartFactory (AChartEngine) org\achartengine\ChartFactory.html
#define IDH_1058	1058	; GraphicalActivity (AChartEngine) org\achartengine\GraphicalActivity.html
#define IDH_1059	1059	; GraphicalView (AChartEngine) org\achartengine\GraphicalView.html
#define IDH_1060	1060	; ITouchHandler (AChartEngine) org\achartengine\ITouchHandler.html
#define IDH_1083	1083	; org.achartengine (AChartEngine) org\achartengine\package-frame.html
#define IDH_1084	1084	; org.achartengine (AChartEngine) org\achartengine\package-summary.html
#define IDH_1085	1085	; org.achartengine Class Hierarchy (AChartEngine) org\achartengine\package-tree.html
#define IDH_1129	1129	; TouchHandler (AChartEngine) org\achartengine\TouchHandler.html
#define IDH_1130	1130	; TouchHandlerOld (AChartEngine) org\achartengine\TouchHandlerOld.html
#define IDH_1086	1086	; Uses of Package org.achartengine (AChartEngine) org\achartengine\package-use.html
#define IDH_1007	1007	; AbstractChart (AChartEngine) org\achartengine\chart\AbstractChart.html
#define IDH_1008	1008	; BarChart (AChartEngine) org\achartengine\chart\BarChart.html
#define IDH_1009	1009	; BarChart.Type (AChartEngine) org\achartengine\chart\BarChart.Type.html
#define IDH_1010	1010	; BubbleChart (AChartEngine) org\achartengine\chart\BubbleChart.html
#define IDH_1031	1031	; ClickableArea (AChartEngine) org\achartengine\chart\ClickableArea.html
#define IDH_1032	1032	; CombinedXYChart (AChartEngine) org\achartengine\chart\CombinedXYChart.html
#define IDH_1033	1033	; CubicLineChart (AChartEngine) org\achartengine\chart\CubicLineChart.html
#define IDH_1034	1034	; DialChart (AChartEngine) org\achartengine\chart\DialChart.html
#define IDH_1035	1035	; DoughnutChart (AChartEngine) org\achartengine\chart\DoughnutChart.html
#define IDH_1036	1036	; LineChart (AChartEngine) org\achartengine\chart\LineChart.html
#define IDH_1037	1037	; org.achartengine.chart (AChartEngine) org\achartengine\chart\package-frame.html
#define IDH_1038	1038	; org.achartengine.chart (AChartEngine) org\achartengine\chart\package-summary.html
#define IDH_1039	1039	; org.achartengine.chart Class Hierarchy (AChartEngine) org\achartengine\chart\package-tree.html
#define IDH_1041	1041	; PieChart (AChartEngine) org\achartengine\chart\PieChart.html
#define IDH_1042	1042	; PieMapper (AChartEngine) org\achartengine\chart\PieMapper.html
#define IDH_1043	1043	; PieSegment (AChartEngine) org\achartengine\chart\PieSegment.html
#define IDH_1044	1044	; PointStyle (AChartEngine) org\achartengine\chart\PointStyle.html
#define IDH_1045	1045	; RangeBarChart (AChartEngine) org\achartengine\chart\RangeBarChart.html
#define IDH_1046	1046	; RangeStackedBarChart (AChartEngine) org\achartengine\chart\RangeStackedBarChart.html
#define IDH_1047	1047	; RoundChart (AChartEngine) org\achartengine\chart\RoundChart.html
#define IDH_1048	1048	; ScatterChart (AChartEngine) org\achartengine\chart\ScatterChart.html
#define IDH_1049	1049	; TimeChart (AChartEngine) org\achartengine\chart\TimeChart.html
#define IDH_1040	1040	; Uses of Package org.achartengine.chart (AChartEngine) org\achartengine\chart\package-use.html
#define IDH_1050	1050	; XYChart (AChartEngine) org\achartengine\chart\XYChart.html
#define IDH_1011	1011	; Uses of Class org.achartengine.chart.AbstractChart (AChartEngine) org\achartengine\chart\class-use\AbstractChart.html
#define IDH_1012	1012	; Uses of Class org.achartengine.chart.BarChart (AChartEngine) org\achartengine\chart\class-use\BarChart.html
#define IDH_1013	1013	; Uses of Class org.achartengine.chart.BarChart.Type (AChartEngine) org\achartengine\chart\class-use\BarChart.Type.html
#define IDH_1014	1014	; Uses of Class org.achartengine.chart.BubbleChart (AChartEngine) org\achartengine\chart\class-use\BubbleChart.html
#define IDH_1015	1015	; Uses of Class org.achartengine.chart.ClickableArea (AChartEngine) org\achartengine\chart\class-use\ClickableArea.html
#define IDH_1016	1016	; Uses of Class org.achartengine.chart.CombinedXYChart (AChartEngine) org\achartengine\chart\class-use\CombinedXYChart.html
#define IDH_1017	1017	; Uses of Class org.achartengine.chart.CubicLineChart (AChartEngine) org\achartengine\chart\class-use\CubicLineChart.html
#define IDH_1018	1018	; Uses of Class org.achartengine.chart.DialChart (AChartEngine) org\achartengine\chart\class-use\DialChart.html
#define IDH_1019	1019	; Uses of Class org.achartengine.chart.DoughnutChart (AChartEngine) org\achartengine\chart\class-use\DoughnutChart.html
#define IDH_1020	1020	; Uses of Class org.achartengine.chart.LineChart (AChartEngine) org\achartengine\chart\class-use\LineChart.html
#define IDH_1021	1021	; Uses of Class org.achartengine.chart.PieChart (AChartEngine) org\achartengine\chart\class-use\PieChart.html
#define IDH_1022	1022	; Uses of Class org.achartengine.chart.PieMapper (AChartEngine) org\achartengine\chart\class-use\PieMapper.html
#define IDH_1023	1023	; Uses of Class org.achartengine.chart.PieSegment (AChartEngine) org\achartengine\chart\class-use\PieSegment.html
#define IDH_1024	1024	; Uses of Class org.achartengine.chart.PointStyle (AChartEngine) org\achartengine\chart\class-use\PointStyle.html
#define IDH_1025	1025	; Uses of Class org.achartengine.chart.RangeBarChart (AChartEngine) org\achartengine\chart\class-use\RangeBarChart.html
#define IDH_1026	1026	; Uses of Class org.achartengine.chart.RangeStackedBarChart (AChartEngine) org\achartengine\chart\class-use\RangeStackedBarChart.html
#define IDH_1027	1027	; Uses of Class org.achartengine.chart.RoundChart (AChartEngine) org\achartengine\chart\class-use\RoundChart.html
#define IDH_1028	1028	; Uses of Class org.achartengine.chart.ScatterChart (AChartEngine) org\achartengine\chart\class-use\ScatterChart.html
#define IDH_1029	1029	; Uses of Class org.achartengine.chart.TimeChart (AChartEngine) org\achartengine\chart\class-use\TimeChart.html
#define IDH_1030	1030	; Uses of Class org.achartengine.chart.XYChart (AChartEngine) org\achartengine\chart\class-use\XYChart.html
#define IDH_1052	1052	; Uses of Class org.achartengine.ChartFactory (AChartEngine) org\achartengine\class-use\ChartFactory.html
#define IDH_1053	1053	; Uses of Class org.achartengine.GraphicalActivity (AChartEngine) org\achartengine\class-use\GraphicalActivity.html
#define IDH_1054	1054	; Uses of Class org.achartengine.GraphicalView (AChartEngine) org\achartengine\class-use\GraphicalView.html
#define IDH_1056	1056	; Uses of Class org.achartengine.TouchHandler (AChartEngine) org\achartengine\class-use\TouchHandler.html
#define IDH_1057	1057	; Uses of Class org.achartengine.TouchHandlerOld (AChartEngine) org\achartengine\class-use\TouchHandlerOld.html
#define IDH_1055	1055	; Uses of Interface org.achartengine.ITouchHandler (AChartEngine) org\achartengine\class-use\ITouchHandler.html
#define IDH_1061	1061	; CategorySeries (AChartEngine) org\achartengine\model\CategorySeries.html
#define IDH_1071	1071	; MultipleCategorySeries (AChartEngine) org\achartengine\model\MultipleCategorySeries.html
#define IDH_1072	1072	; org.achartengine.model (AChartEngine) org\achartengine\model\package-frame.html
#define IDH_1073	1073	; org.achartengine.model (AChartEngine) org\achartengine\model\package-summary.html
#define IDH_1074	1074	; org.achartengine.model Class Hierarchy (AChartEngine) org\achartengine\model\package-tree.html
#define IDH_1076	1076	; Point (AChartEngine) org\achartengine\model\Point.html
#define IDH_1077	1077	; RangeCategorySeries (AChartEngine) org\achartengine\model\RangeCategorySeries.html
#define IDH_1078	1078	; SeriesSelection (AChartEngine) org\achartengine\model\SeriesSelection.html
#define IDH_1079	1079	; TimeSeries (AChartEngine) org\achartengine\model\TimeSeries.html
#define IDH_1075	1075	; Uses of Package org.achartengine.model (AChartEngine) org\achartengine\model\package-use.html
#define IDH_1080	1080	; XYMultipleSeriesDataset (AChartEngine) org\achartengine\model\XYMultipleSeriesDataset.html
#define IDH_1081	1081	; XYSeries (AChartEngine) org\achartengine\model\XYSeries.html
#define IDH_1082	1082	; XYValueSeries (AChartEngine) org\achartengine\model\XYValueSeries.html
#define IDH_1062	1062	; Uses of Class org.achartengine.model.CategorySeries (AChartEngine) org\achartengine\model\class-use\CategorySeries.html
#define IDH_1063	1063	; Uses of Class org.achartengine.model.MultipleCategorySeries (AChartEngine) org\achartengine\model\class-use\MultipleCategorySeries.html
#define IDH_1064	1064	; Uses of Class org.achartengine.model.Point (AChartEngine) org\achartengine\model\class-use\Point.html
#define IDH_1065	1065	; Uses of Class org.achartengine.model.RangeCategorySeries (AChartEngine) org\achartengine\model\class-use\RangeCategorySeries.html
#define IDH_1066	1066	; Uses of Class org.achartengine.model.SeriesSelection (AChartEngine) org\achartengine\model\class-use\SeriesSelection.html
#define IDH_1067	1067	; Uses of Class org.achartengine.model.TimeSeries (AChartEngine) org\achartengine\model\class-use\TimeSeries.html
#define IDH_1068	1068	; Uses of Class org.achartengine.model.XYMultipleSeriesDataset (AChartEngine) org\achartengine\model\class-use\XYMultipleSeriesDataset.html
#define IDH_1069	1069	; Uses of Class org.achartengine.model.XYSeries (AChartEngine) org\achartengine\model\class-use\XYSeries.html
#define IDH_1070	1070	; Uses of Class org.achartengine.model.XYValueSeries (AChartEngine) org\achartengine\model\class-use\XYValueSeries.html
#define IDH_1087	1087	; BasicStroke (AChartEngine) org\achartengine\renderer\BasicStroke.html
#define IDH_1098	1098	; DefaultRenderer (AChartEngine) org\achartengine\renderer\DefaultRenderer.html
#define IDH_1099	1099	; DialRenderer (AChartEngine) org\achartengine\renderer\DialRenderer.html
#define IDH_1100	1100	; DialRenderer.Type (AChartEngine) org\achartengine\renderer\DialRenderer.Type.html
#define IDH_1101	1101	; org.achartengine.renderer (AChartEngine) org\achartengine\renderer\package-frame.html
#define IDH_1102	1102	; org.achartengine.renderer (AChartEngine) org\achartengine\renderer\package-summary.html
#define IDH_1103	1103	; org.achartengine.renderer Class Hierarchy (AChartEngine) org\achartengine\renderer\package-tree.html
#define IDH_1105	1105	; SimpleSeriesRenderer (AChartEngine) org\achartengine\renderer\SimpleSeriesRenderer.html
#define IDH_1104	1104	; Uses of Package org.achartengine.renderer (AChartEngine) org\achartengine\renderer\package-use.html
#define IDH_1106	1106	; XYMultipleSeriesRenderer (AChartEngine) org\achartengine\renderer\XYMultipleSeriesRenderer.html
#define IDH_1107	1107	; XYMultipleSeriesRenderer.Orientation (AChartEngine) org\achartengine\renderer\XYMultipleSeriesRenderer.Orientation.html
#define IDH_1110	1110	; XYSeriesRenderer (AChartEngine) org\achartengine\renderer\XYSeriesRenderer.html
#define IDH_1108	1108	; XYSeriesRenderer.FillOutsideLine (AChartEngine) org\achartengine\renderer\XYSeriesRenderer.FillOutsideLine.html
#define IDH_1109	1109	; XYSeriesRenderer.FillOutsideLine.Type (AChartEngine) org\achartengine\renderer\XYSeriesRenderer.FillOutsideLine.Type.html
#define IDH_1088	1088	; Uses of Class org.achartengine.renderer.BasicStroke (AChartEngine) org\achartengine\renderer\class-use\BasicStroke.html
#define IDH_1089	1089	; Uses of Class org.achartengine.renderer.DefaultRenderer (AChartEngine) org\achartengine\renderer\class-use\DefaultRenderer.html
#define IDH_1090	1090	; Uses of Class org.achartengine.renderer.DialRenderer (AChartEngine) org\achartengine\renderer\class-use\DialRenderer.html
#define IDH_1091	1091	; Uses of Class org.achartengine.renderer.DialRenderer.Type (AChartEngine) org\achartengine\renderer\class-use\DialRenderer.Type.html
#define IDH_1092	1092	; Uses of Class org.achartengine.renderer.SimpleSeriesRenderer (AChartEngine) org\achartengine\renderer\class-use\SimpleSeriesRenderer.html
#define IDH_1093	1093	; Uses of Class org.achartengine.renderer.XYMultipleSeriesRenderer (AChartEngine) org\achartengine\renderer\class-use\XYMultipleSeriesRenderer.html
#define IDH_1094	1094	; Uses of Class org.achartengine.renderer.XYMultipleSeriesRenderer.Orientation (AChartEngine) org\achartengine\renderer\class-use\XYMultipleSeriesRenderer.Orientation.html
#define IDH_1097	1097	; Uses of Class org.achartengine.renderer.XYSeriesRenderer (AChartEngine) org\achartengine\renderer\class-use\XYSeriesRenderer.html
#define IDH_1095	1095	; Uses of Class org.achartengine.renderer.XYSeriesRenderer.FillOutsideLine (AChartEngine) org\achartengine\renderer\class-use\XYSeriesRenderer.FillOutsideLine.html
#define IDH_1096	1096	; Uses of Class org.achartengine.renderer.XYSeriesRenderer.FillOutsideLine.Type (AChartEngine) org\achartengine\renderer\class-use\XYSeriesRenderer.FillOutsideLine.Type.html
#define IDH_1111	1111	; AbstractTool (AChartEngine) org\achartengine\tools\AbstractTool.html
#define IDH_1119	1119	; FitZoom (AChartEngine) org\achartengine\tools\FitZoom.html
#define IDH_1120	1120	; org.achartengine.tools (AChartEngine) org\achartengine\tools\package-frame.html
#define IDH_1121	1121	; org.achartengine.tools (AChartEngine) org\achartengine\tools\package-summary.html
#define IDH_1122	1122	; org.achartengine.tools Class Hierarchy (AChartEngine) org\achartengine\tools\package-tree.html
#define IDH_1124	1124	; Pan (AChartEngine) org\achartengine\tools\Pan.html
#define IDH_1125	1125	; PanListener (AChartEngine) org\achartengine\tools\PanListener.html
#define IDH_1123	1123	; Uses of Package org.achartengine.tools (AChartEngine) org\achartengine\tools\package-use.html
#define IDH_1126	1126	; Zoom (AChartEngine) org\achartengine\tools\Zoom.html
#define IDH_1127	1127	; ZoomEvent (AChartEngine) org\achartengine\tools\ZoomEvent.html
#define IDH_1128	1128	; ZoomListener (AChartEngine) org\achartengine\tools\ZoomListener.html
#define IDH_1112	1112	; Uses of Class org.achartengine.tools.AbstractTool (AChartEngine) org\achartengine\tools\class-use\AbstractTool.html
#define IDH_1113	1113	; Uses of Class org.achartengine.tools.FitZoom (AChartEngine) org\achartengine\tools\class-use\FitZoom.html
#define IDH_1114	1114	; Uses of Class org.achartengine.tools.Pan (AChartEngine) org\achartengine\tools\class-use\Pan.html
#define IDH_1116	1116	; Uses of Class org.achartengine.tools.Zoom (AChartEngine) org\achartengine\tools\class-use\Zoom.html
#define IDH_1117	1117	; Uses of Class org.achartengine.tools.ZoomEvent (AChartEngine) org\achartengine\tools\class-use\ZoomEvent.html
#define IDH_1115	1115	; Uses of Interface org.achartengine.tools.PanListener (AChartEngine) org\achartengine\tools\class-use\PanListener.html
#define IDH_1118	1118	; Uses of Interface org.achartengine.tools.ZoomListener (AChartEngine) org\achartengine\tools\class-use\ZoomListener.html
#define IDH_1134	1134	; IndexXYMap (AChartEngine) org\achartengine\util\IndexXYMap.html
#define IDH_1135	1135	; MathHelper (AChartEngine) org\achartengine\util\MathHelper.html
#define IDH_1136	1136	; org.achartengine.util (AChartEngine) org\achartengine\util\package-frame.html
#define IDH_1137	1137	; org.achartengine.util (AChartEngine) org\achartengine\util\package-summary.html
#define IDH_1138	1138	; org.achartengine.util Class Hierarchy (AChartEngine) org\achartengine\util\package-tree.html
#define IDH_1139	1139	; Uses of Package org.achartengine.util (AChartEngine) org\achartengine\util\package-use.html
#define IDH_1140	1140	; XYEntry (AChartEngine) org\achartengine\util\XYEntry.html
#define IDH_1131	1131	; Uses of Class org.achartengine.util.IndexXYMap (AChartEngine) org\achartengine\util\class-use\IndexXYMap.html
#define IDH_1132	1132	; Uses of Class org.achartengine.util.MathHelper (AChartEngine) org\achartengine\util\class-use\MathHelper.html
#define IDH_1133	1133	; Uses of Class org.achartengine.util.XYEntry (AChartEngine) org\achartengine\util\class-use\XYEntry.html
